# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/weihua/Desktop/meta_sys

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/weihua/Desktop/meta_sys/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/weihua/Desktop/meta_sys/build/CMakeFiles /home/weihua/Desktop/meta_sys/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/weihua/Desktop/meta_sys/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named deepsort

# Build rule for target.
deepsort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deepsort
.PHONY : deepsort

# fast build rule for target.
deepsort/fast:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/build
.PHONY : deepsort/fast

#=============================================================================
# Target rules for targets named yolov5_pro

# Build rule for target.
yolov5_pro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yolov5_pro
.PHONY : yolov5_pro

# fast build rule for target.
yolov5_pro/fast:
	$(MAKE) -f CMakeFiles/yolov5_pro.dir/build.make CMakeFiles/yolov5_pro.dir/build
.PHONY : yolov5_pro/fast

#=============================================================================
# Target rules for targets named myplugins

# Build rule for target.
myplugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myplugins
.PHONY : myplugins

# fast build rule for target.
myplugins/fast:
	$(MAKE) -f CMakeFiles/myplugins.dir/build.make CMakeFiles/myplugins.dir/build
.PHONY : myplugins/fast

DeepSORT/DeepAppearanceDescriptor/model.o: DeepSORT/DeepAppearanceDescriptor/model.cpp.o

.PHONY : DeepSORT/DeepAppearanceDescriptor/model.o

# target to build an object file
DeepSORT/DeepAppearanceDescriptor/model.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/DeepAppearanceDescriptor/model.cpp.o
.PHONY : DeepSORT/DeepAppearanceDescriptor/model.cpp.o

DeepSORT/DeepAppearanceDescriptor/model.i: DeepSORT/DeepAppearanceDescriptor/model.cpp.i

.PHONY : DeepSORT/DeepAppearanceDescriptor/model.i

# target to preprocess a source file
DeepSORT/DeepAppearanceDescriptor/model.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/DeepAppearanceDescriptor/model.cpp.i
.PHONY : DeepSORT/DeepAppearanceDescriptor/model.cpp.i

DeepSORT/DeepAppearanceDescriptor/model.s: DeepSORT/DeepAppearanceDescriptor/model.cpp.s

.PHONY : DeepSORT/DeepAppearanceDescriptor/model.s

# target to generate assembly for a file
DeepSORT/DeepAppearanceDescriptor/model.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/DeepAppearanceDescriptor/model.cpp.s
.PHONY : DeepSORT/DeepAppearanceDescriptor/model.cpp.s

DeepSORT/KalmanFilter/kalmanfilter.o: DeepSORT/KalmanFilter/kalmanfilter.cpp.o

.PHONY : DeepSORT/KalmanFilter/kalmanfilter.o

# target to build an object file
DeepSORT/KalmanFilter/kalmanfilter.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/kalmanfilter.cpp.o
.PHONY : DeepSORT/KalmanFilter/kalmanfilter.cpp.o

DeepSORT/KalmanFilter/kalmanfilter.i: DeepSORT/KalmanFilter/kalmanfilter.cpp.i

.PHONY : DeepSORT/KalmanFilter/kalmanfilter.i

# target to preprocess a source file
DeepSORT/KalmanFilter/kalmanfilter.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/kalmanfilter.cpp.i
.PHONY : DeepSORT/KalmanFilter/kalmanfilter.cpp.i

DeepSORT/KalmanFilter/kalmanfilter.s: DeepSORT/KalmanFilter/kalmanfilter.cpp.s

.PHONY : DeepSORT/KalmanFilter/kalmanfilter.s

# target to generate assembly for a file
DeepSORT/KalmanFilter/kalmanfilter.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/kalmanfilter.cpp.s
.PHONY : DeepSORT/KalmanFilter/kalmanfilter.cpp.s

DeepSORT/KalmanFilter/linear_assignment.o: DeepSORT/KalmanFilter/linear_assignment.cpp.o

.PHONY : DeepSORT/KalmanFilter/linear_assignment.o

# target to build an object file
DeepSORT/KalmanFilter/linear_assignment.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/linear_assignment.cpp.o
.PHONY : DeepSORT/KalmanFilter/linear_assignment.cpp.o

DeepSORT/KalmanFilter/linear_assignment.i: DeepSORT/KalmanFilter/linear_assignment.cpp.i

.PHONY : DeepSORT/KalmanFilter/linear_assignment.i

# target to preprocess a source file
DeepSORT/KalmanFilter/linear_assignment.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/linear_assignment.cpp.i
.PHONY : DeepSORT/KalmanFilter/linear_assignment.cpp.i

DeepSORT/KalmanFilter/linear_assignment.s: DeepSORT/KalmanFilter/linear_assignment.cpp.s

.PHONY : DeepSORT/KalmanFilter/linear_assignment.s

# target to generate assembly for a file
DeepSORT/KalmanFilter/linear_assignment.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/linear_assignment.cpp.s
.PHONY : DeepSORT/KalmanFilter/linear_assignment.cpp.s

DeepSORT/KalmanFilter/nn_matching.o: DeepSORT/KalmanFilter/nn_matching.cpp.o

.PHONY : DeepSORT/KalmanFilter/nn_matching.o

# target to build an object file
DeepSORT/KalmanFilter/nn_matching.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/nn_matching.cpp.o
.PHONY : DeepSORT/KalmanFilter/nn_matching.cpp.o

DeepSORT/KalmanFilter/nn_matching.i: DeepSORT/KalmanFilter/nn_matching.cpp.i

.PHONY : DeepSORT/KalmanFilter/nn_matching.i

# target to preprocess a source file
DeepSORT/KalmanFilter/nn_matching.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/nn_matching.cpp.i
.PHONY : DeepSORT/KalmanFilter/nn_matching.cpp.i

DeepSORT/KalmanFilter/nn_matching.s: DeepSORT/KalmanFilter/nn_matching.cpp.s

.PHONY : DeepSORT/KalmanFilter/nn_matching.s

# target to generate assembly for a file
DeepSORT/KalmanFilter/nn_matching.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/nn_matching.cpp.s
.PHONY : DeepSORT/KalmanFilter/nn_matching.cpp.s

DeepSORT/KalmanFilter/track.o: DeepSORT/KalmanFilter/track.cpp.o

.PHONY : DeepSORT/KalmanFilter/track.o

# target to build an object file
DeepSORT/KalmanFilter/track.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/track.cpp.o
.PHONY : DeepSORT/KalmanFilter/track.cpp.o

DeepSORT/KalmanFilter/track.i: DeepSORT/KalmanFilter/track.cpp.i

.PHONY : DeepSORT/KalmanFilter/track.i

# target to preprocess a source file
DeepSORT/KalmanFilter/track.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/track.cpp.i
.PHONY : DeepSORT/KalmanFilter/track.cpp.i

DeepSORT/KalmanFilter/track.s: DeepSORT/KalmanFilter/track.cpp.s

.PHONY : DeepSORT/KalmanFilter/track.s

# target to generate assembly for a file
DeepSORT/KalmanFilter/track.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/track.cpp.s
.PHONY : DeepSORT/KalmanFilter/track.cpp.s

DeepSORT/KalmanFilter/tracker.o: DeepSORT/KalmanFilter/tracker.cpp.o

.PHONY : DeepSORT/KalmanFilter/tracker.o

# target to build an object file
DeepSORT/KalmanFilter/tracker.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/tracker.cpp.o
.PHONY : DeepSORT/KalmanFilter/tracker.cpp.o

DeepSORT/KalmanFilter/tracker.i: DeepSORT/KalmanFilter/tracker.cpp.i

.PHONY : DeepSORT/KalmanFilter/tracker.i

# target to preprocess a source file
DeepSORT/KalmanFilter/tracker.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/tracker.cpp.i
.PHONY : DeepSORT/KalmanFilter/tracker.cpp.i

DeepSORT/KalmanFilter/tracker.s: DeepSORT/KalmanFilter/tracker.cpp.s

.PHONY : DeepSORT/KalmanFilter/tracker.s

# target to generate assembly for a file
DeepSORT/KalmanFilter/tracker.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/KalmanFilter/tracker.cpp.s
.PHONY : DeepSORT/KalmanFilter/tracker.cpp.s

DeepSORT/MunkresAssignment/hungarianoper.o: DeepSORT/MunkresAssignment/hungarianoper.cpp.o

.PHONY : DeepSORT/MunkresAssignment/hungarianoper.o

# target to build an object file
DeepSORT/MunkresAssignment/hungarianoper.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/MunkresAssignment/hungarianoper.cpp.o
.PHONY : DeepSORT/MunkresAssignment/hungarianoper.cpp.o

DeepSORT/MunkresAssignment/hungarianoper.i: DeepSORT/MunkresAssignment/hungarianoper.cpp.i

.PHONY : DeepSORT/MunkresAssignment/hungarianoper.i

# target to preprocess a source file
DeepSORT/MunkresAssignment/hungarianoper.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/MunkresAssignment/hungarianoper.cpp.i
.PHONY : DeepSORT/MunkresAssignment/hungarianoper.cpp.i

DeepSORT/MunkresAssignment/hungarianoper.s: DeepSORT/MunkresAssignment/hungarianoper.cpp.s

.PHONY : DeepSORT/MunkresAssignment/hungarianoper.s

# target to generate assembly for a file
DeepSORT/MunkresAssignment/hungarianoper.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/MunkresAssignment/hungarianoper.cpp.s
.PHONY : DeepSORT/MunkresAssignment/hungarianoper.cpp.s

DeepSORT/MunkresAssignment/munkres/munkres.o: DeepSORT/MunkresAssignment/munkres/munkres.cpp.o

.PHONY : DeepSORT/MunkresAssignment/munkres/munkres.o

# target to build an object file
DeepSORT/MunkresAssignment/munkres/munkres.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/MunkresAssignment/munkres/munkres.cpp.o
.PHONY : DeepSORT/MunkresAssignment/munkres/munkres.cpp.o

DeepSORT/MunkresAssignment/munkres/munkres.i: DeepSORT/MunkresAssignment/munkres/munkres.cpp.i

.PHONY : DeepSORT/MunkresAssignment/munkres/munkres.i

# target to preprocess a source file
DeepSORT/MunkresAssignment/munkres/munkres.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/MunkresAssignment/munkres/munkres.cpp.i
.PHONY : DeepSORT/MunkresAssignment/munkres/munkres.cpp.i

DeepSORT/MunkresAssignment/munkres/munkres.s: DeepSORT/MunkresAssignment/munkres/munkres.cpp.s

.PHONY : DeepSORT/MunkresAssignment/munkres/munkres.s

# target to generate assembly for a file
DeepSORT/MunkresAssignment/munkres/munkres.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/MunkresAssignment/munkres/munkres.cpp.s
.PHONY : DeepSORT/MunkresAssignment/munkres/munkres.cpp.s

DeepSORT/track_deepsort.o: DeepSORT/track_deepsort.cpp.o

.PHONY : DeepSORT/track_deepsort.o

# target to build an object file
DeepSORT/track_deepsort.cpp.o:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/track_deepsort.cpp.o
.PHONY : DeepSORT/track_deepsort.cpp.o

DeepSORT/track_deepsort.i: DeepSORT/track_deepsort.cpp.i

.PHONY : DeepSORT/track_deepsort.i

# target to preprocess a source file
DeepSORT/track_deepsort.cpp.i:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/track_deepsort.cpp.i
.PHONY : DeepSORT/track_deepsort.cpp.i

DeepSORT/track_deepsort.s: DeepSORT/track_deepsort.cpp.s

.PHONY : DeepSORT/track_deepsort.s

# target to generate assembly for a file
DeepSORT/track_deepsort.cpp.s:
	$(MAKE) -f CMakeFiles/deepsort.dir/build.make CMakeFiles/deepsort.dir/DeepSORT/track_deepsort.cpp.s
.PHONY : DeepSORT/track_deepsort.cpp.s

calibrator.o: calibrator.cpp.o

.PHONY : calibrator.o

# target to build an object file
calibrator.cpp.o:
	$(MAKE) -f CMakeFiles/yolov5_pro.dir/build.make CMakeFiles/yolov5_pro.dir/calibrator.cpp.o
.PHONY : calibrator.cpp.o

calibrator.i: calibrator.cpp.i

.PHONY : calibrator.i

# target to preprocess a source file
calibrator.cpp.i:
	$(MAKE) -f CMakeFiles/yolov5_pro.dir/build.make CMakeFiles/yolov5_pro.dir/calibrator.cpp.i
.PHONY : calibrator.cpp.i

calibrator.s: calibrator.cpp.s

.PHONY : calibrator.s

# target to generate assembly for a file
calibrator.cpp.s:
	$(MAKE) -f CMakeFiles/yolov5_pro.dir/build.make CMakeFiles/yolov5_pro.dir/calibrator.cpp.s
.PHONY : calibrator.cpp.s

yolov5_pro.o: yolov5_pro.cpp.o

.PHONY : yolov5_pro.o

# target to build an object file
yolov5_pro.cpp.o:
	$(MAKE) -f CMakeFiles/yolov5_pro.dir/build.make CMakeFiles/yolov5_pro.dir/yolov5_pro.cpp.o
.PHONY : yolov5_pro.cpp.o

yolov5_pro.i: yolov5_pro.cpp.i

.PHONY : yolov5_pro.i

# target to preprocess a source file
yolov5_pro.cpp.i:
	$(MAKE) -f CMakeFiles/yolov5_pro.dir/build.make CMakeFiles/yolov5_pro.dir/yolov5_pro.cpp.i
.PHONY : yolov5_pro.cpp.i

yolov5_pro.s: yolov5_pro.cpp.s

.PHONY : yolov5_pro.s

# target to generate assembly for a file
yolov5_pro.cpp.s:
	$(MAKE) -f CMakeFiles/yolov5_pro.dir/build.make CMakeFiles/yolov5_pro.dir/yolov5_pro.cpp.s
.PHONY : yolov5_pro.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... deepsort"
	@echo "... rebuild_cache"
	@echo "... yolov5_pro"
	@echo "... myplugins"
	@echo "... DeepSORT/DeepAppearanceDescriptor/model.o"
	@echo "... DeepSORT/DeepAppearanceDescriptor/model.i"
	@echo "... DeepSORT/DeepAppearanceDescriptor/model.s"
	@echo "... DeepSORT/KalmanFilter/kalmanfilter.o"
	@echo "... DeepSORT/KalmanFilter/kalmanfilter.i"
	@echo "... DeepSORT/KalmanFilter/kalmanfilter.s"
	@echo "... DeepSORT/KalmanFilter/linear_assignment.o"
	@echo "... DeepSORT/KalmanFilter/linear_assignment.i"
	@echo "... DeepSORT/KalmanFilter/linear_assignment.s"
	@echo "... DeepSORT/KalmanFilter/nn_matching.o"
	@echo "... DeepSORT/KalmanFilter/nn_matching.i"
	@echo "... DeepSORT/KalmanFilter/nn_matching.s"
	@echo "... DeepSORT/KalmanFilter/track.o"
	@echo "... DeepSORT/KalmanFilter/track.i"
	@echo "... DeepSORT/KalmanFilter/track.s"
	@echo "... DeepSORT/KalmanFilter/tracker.o"
	@echo "... DeepSORT/KalmanFilter/tracker.i"
	@echo "... DeepSORT/KalmanFilter/tracker.s"
	@echo "... DeepSORT/MunkresAssignment/hungarianoper.o"
	@echo "... DeepSORT/MunkresAssignment/hungarianoper.i"
	@echo "... DeepSORT/MunkresAssignment/hungarianoper.s"
	@echo "... DeepSORT/MunkresAssignment/munkres/munkres.o"
	@echo "... DeepSORT/MunkresAssignment/munkres/munkres.i"
	@echo "... DeepSORT/MunkresAssignment/munkres/munkres.s"
	@echo "... DeepSORT/track_deepsort.o"
	@echo "... DeepSORT/track_deepsort.i"
	@echo "... DeepSORT/track_deepsort.s"
	@echo "... calibrator.o"
	@echo "... calibrator.i"
	@echo "... calibrator.s"
	@echo "... yolov5_pro.o"
	@echo "... yolov5_pro.i"
	@echo "... yolov5_pro.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

